# Generated by Django 2.2.16 on 2020-10-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0303_realm_wildcard_mention_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default=3),
        ),
    ]
